version: '3.11'

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: "${USER}_hirag-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ofnil-agentic-rag:
    image: sagicuhk/sagi:latest
    container_name: "${USER}_hirag-prod"
    volumes:
      - ${HIRAG_PROD_DIR}:/chatbot
    cap_add:
      - SYS_ADMIN
    command: ["tail", "-f", "/dev/null"]  # keep docker running
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
