version: '3.11'

networks:
  app-network:
    driver: bridge

services:
  ofnil-agentic-rag:
    image: sagicuhk/sagi:latest
    container_name: "${USER}_hirag-prod"
    volumes:
      - ${HIRAG_PROD_DIR}:/chatbot
    cap_add:
      - SYS_ADMIN
    command: ["tail", "-f", "/dev/null"]  # keep docker running
    restart: unless-stopped
    networks:
      - app-network
