name: Pylint

on: 
  pull_request:
      branches:
        - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install black==25.1.0
        pip install blackdoc==0.4.0
        pip install isort
        pip install autoflake

    - name: Lint Python
      run: |
        black --check $(git ls-files '*.py')
        blackdoc --check $(git ls-files '*.py')
        isort --check $(git ls-files '*.py') --profile black
        autoflake --in-place --remove-unused-variables $(git ls-files '*.py')
